/**
 * Tests for scanner module generated by GPT-6 Luna.
 */

import { PassThrough } from 'node:stream'
import { afterEach, describe, expect, it, vi } from 'vitest'
import Scanner from '../src/module/scanner.js'

const createScanner = async (contents = '') => {
  const input = new PassThrough()
  const output = { write: vi.fn() }
  const scanner = new Scanner({ input, output })

  input.end(contents)
  await new Promise(resolve => setImmediate(resolve))

  return { scanner, output }
}

afterEach(() => {
  vi.restoreAllMocks()
})

describe('Scanner line and token reading', () => {
  it('reads full lines and marks EOF when no line remains', async () => {
    const { scanner } = await createScanner(' first line  \nsecond line\n')

    await expect(scanner.nextLine()).resolves.toBe(' first line  ')
    await expect(scanner.nextLine()).resolves.toBe('second line')
    await expect(scanner.nextLine()).rejects.toMatchObject({ name: 'EndOfFileError' })
    expect(scanner.eof).toBe(true)
  })

  it('splits tokens on whitespace and skips empty or whitespace-only lines', async () => {
    const { scanner } = await createScanner('\n  \t \n one\t two   three  \n')

    await expect(scanner.nextTokens()).resolves.toEqual(['one', 'two', 'three'])
  })

  it('returns existing buffered tokens and reports EOF when no tokens can be filled', async () => {
    const { scanner } = await createScanner('one two\n')

    await expect(scanner.next()).resolves.toBe('one')
    await expect(scanner.nextTokens()).resolves.toEqual(['two'])
    await expect(scanner.nextTokens()).rejects.toMatchObject({ name: 'EndOfFileError' })
  })

  it('returns tokens one at a time, then reports EOF', async () => {
    const { scanner } = await createScanner('alpha beta\n')

    await expect(scanner.next()).resolves.toBe('alpha')
    await expect(scanner.next()).resolves.toBe('beta')
    await expect(scanner.next()).rejects.toMatchObject({ name: 'EndOfFileError' })
    expect(scanner.eof).toBe(true)
  })

  it('waits for the next line and resolves when the input closes', async () => {
    const { scanner } = await createScanner('ready\n')

    await expect(scanner.pauseUntilNext()).resolves.toBeUndefined()
    await expect(scanner.pauseUntilNext()).resolves.toBeUndefined()
  })

  it('reports queued lines and buffered tokens through hasNext', async () => {
    const { scanner } = await createScanner('one two\nnext\n')

    expect(scanner.hasNext()).toBe(true)
    await expect(scanner.next()).resolves.toBe('one')
    expect(scanner.hasNext()).toBe(true)
    await expect(scanner.next()).resolves.toBe('two')
    expect(scanner.hasNext()).toBe(true)
    await expect(scanner.next()).resolves.toBe('next')
    expect(scanner.hasNext()).toBe(false)
  })

  it('clears the current tokens and queued lines', async () => {
    const { scanner } = await createScanner('one two\nqueued\n')

    await expect(scanner.next()).resolves.toBe('one')
    expect(scanner.clearInput()).toBe(scanner)
    expect(scanner.hasNext()).toBe(false)
    await expect(scanner.next()).rejects.toMatchObject({ name: 'EndOfFileError' })
  })
})

describe('Scanner number and string validation', () => {
  it.each([
    ['42', 42],
    ['-12', -12],
    ['+12.50', 12.5],
    ['.75', 0.75],
    ['12.', 12],
    ['-1.25e+2', -125],
    ['2E-2', 0.02],
  ])('parses valid number %s', async (token, expected) => {
    const { scanner } = await createScanner(`${token}\n`)

    await expect(scanner.nextNumber()).resolves.toBe(expected)
  })

  it.each(['.', '+', '1e', '1e+', '1e2e3', '1.2.3', 'Infinity', '0x10'])('rejects invalid number %j', async token => {
    const { scanner } = await createScanner(`${token}\n`)

    await expect(scanner.nextNumber()).rejects.toBeInstanceOf(TypeError)
  })

  it('rejects a numeric conversion that unexpectedly returns NaN', async () => {
    const { scanner } = await createScanner('1\n')
    vi.spyOn(Number, 'parseFloat').mockReturnValue(Number.NaN)

    await expect(scanner.nextNumber()).rejects.toThrow("'1' could not be converted to number")
  })

  it('accepts inclusive numeric range boundaries and ignores non-number bounds', async () => {
    const { scanner } = await createScanner('0 10 5\n')

    await expect(scanner.nextNumber({ min: 0, max: 0 })).resolves.toBe(0)
    await expect(scanner.nextNumber({ min: 10, max: 10 })).resolves.toBe(10)
    await expect(scanner.nextNumber({ min: '4', max: null })).resolves.toBe(5)
  })

  it.each([
    ['1', { min: 2 }],
    ['3', { max: 2 }],
  ])('rejects number %s outside its range', async (token, range) => {
    const { scanner } = await createScanner(`${token}\n`)

    await expect(scanner.nextNumber(range)).rejects.toBeInstanceOf(RangeError)
    await expect(scanner.nextNumber()).rejects.toMatchObject({ name: 'EndOfFileError' })
  })

  it('matches strings with a regular expression and enforces inclusive length limits', async () => {
    const { scanner } = await createScanner('hello world\n')

    await expect(scanner.nextString({ pattern: /^hello$/, min: 5, max: 5 })).resolves.toBe('hello')
    await expect(scanner.nextString({ min: 6, max: 6 })).rejects.toBeInstanceOf(RangeError)
  })

  it('rejects regex mismatches before checking the string length', async () => {
    const { scanner } = await createScanner('abc\n')

    await expect(scanner.nextString({ pattern: /^z/, min: 100 })).rejects.toMatchObject({
      name: 'RegExpDoesNotMatchError',
    })
  })

  it('ignores a non-regex pattern and supports either length bound independently', async () => {
    const { scanner } = await createScanner('a abc\n')

    await expect(scanner.nextString({ pattern: 'not a regex', max: 1 })).resolves.toBe('a')
    await expect(scanner.nextString({ min: 3 })).resolves.toBe('abc')
  })

  it.each([
    ['a', { min: 2 }],
    ['abc', { max: 2 }],
  ])('rejects string %j outside its length range', async (token, range) => {
    const { scanner } = await createScanner(`${token}\n`)

    await expect(scanner.nextString(range)).rejects.toBeInstanceOf(RangeError)
  })
})

describe('Scanner output and named buffers', () => {
  it('writes prompts and returns the scanner for chaining', async () => {
    const { scanner, output } = await createScanner()

    expect(scanner.prompt('Enter value: ')).toBe(scanner)
    expect(output.write).toHaveBeenCalledWith('Enter value: ')
  })

  it('creates named buffers, saves copies, and restores pushed snapshots', async () => {
    const { scanner } = await createScanner('first second third\n')

    await scanner.next()
    scanner.saveBuffer('copy')
    scanner.useBuffer('copy')
    await expect(scanner.next()).resolves.toBe('second')

    scanner.pushBuffer()
    await expect(scanner.next()).resolves.toBe('third')
    scanner.popBuffer()
    await expect(scanner.next()).resolves.toBe('third')

    scanner.useBuffer('default')
    await expect(scanner.next()).resolves.toBe('second')
    expect(() => scanner.popBuffer()).toThrow('No buffers to pop')
  })

  it('switches to the default buffer when the active buffer is removed', async () => {
    const { scanner } = await createScanner('default-token\n')

    scanner.useBuffer('temporary')
    scanner.removeBuffer('temporary')
    await expect(scanner.next()).resolves.toBe('default-token')
    expect(() => scanner.removeBuffer('default')).toThrow('Cannot remove the default buffer')
  })
})